import styled from 'styled-components';
export const BtnAdd = styled.div`
  cursor: pointer;
  display: flex;
  width: 12.8rem;
  padding: 1rem 0rem;
  justify-content: center;
  align-items: center;
  gap: 0.625rem;
  border-radius: 0.75rem;
  background: #2fc4b2;
  color: #fff;
  text-align: center;
  font-family: Pretendard;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
`;
export const BtnSave = styled.div`
  cursor: pointer;
  display: flex;
  width: 95%;
  padding: 1rem 0rem;
  justify-content: center;
  align-items: center;
  gap: 0.625rem;
  border-radius: 0.75rem;
  background: #2fc4b2;
  color: #fff;
  text-align: center;
  font-family: Pretendard;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
`;
export const BtnSaveNo = styled.div`
  cursor: pointer;
  display: flex;
  width: 95%;
  padding: 1rem 0rem;
  justify-content: center;
  align-items: center;
  gap: 0.625rem;
  border-radius: 0.75rem;
  background: #dee2e6;
  color: #fff;
  text-align: center;
  font-family: Pretendard;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
`;
export const BtnOut = styled.div`
  cursor: pointer;
  margin-right: 0.5rem;
  width: 7.5rem;
  display: inline-flex;
  padding: 1rem 0rem;
  justify-content: center;
  align-items: center;
  gap: 0.625rem;
  border-radius: 0.75rem;
  background: #adb5bd;
  color: #fff;
  text-align: center;
  font-family: Pretendard;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
`;
export const BtnModal = styled.div`
  cursor: pointer;
  width: 9rem;
  padding: 1rem 0rem;
  margin-top: 8.5rem;
  margin-left: 6.2rem;
  display: flex;
  border-radius: 0.75rem;
  background: #2fc4b2;
  color: #fff;
  text-align: center;
  align-items: center;
  justify-content: center;
  font-family: Pretendard;
  font-size: 1.1rem;
  font-style: normal;
  font-weight: 700;
  line-height: normal;
  cursor: pointer;
`;
