import './globals.css';
import type { Metadata } from 'next';
import Providers from '@/components/Provider/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          {children}
          <div id="senior-info-portal"></div>
        </Providers>
      </body>
    </html>
  );
}
