import './globals.css';
import type { Metadata } from 'next';
import { KakaoAccessProvider } from '../context/KakaoAccessProvider';
import { SeverAccessProvider } from '../context/SeverAccessProvider';
import Providers from '@/components/Provider/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <SeverAccessProvider>
            <KakaoAccessProvider>{children}</KakaoAccessProvider>
          </SeverAccessProvider>
        </Providers>
      </body>
    </html>
  );
}
