import './globals.css'
import type { Metadata } from 'next'
import { KakaoAccessProvider } from './context/KakaoAccessProvider'
import {SeverAccessProvider} from './context/SeverAccessProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <SeverAccessProvider>
        <KakaoAccessProvider>
          {children}
        </KakaoAccessProvider>
        </SeverAccessProvider>
      </body>
    </html>
  )
}
